services:
  website:
    network_mode: "host"
    container_name: website
    image: website
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: "/website"
    user: 1000:1000
    stop_grace_period: 1s
    command: sh -c "bun install && bun dev"
    volumes:
      - ./:/website
